force-app/main/default/objects/IF_Account__c/IF_Account__c.object-meta.xml
<CustomObject>
    <label>IF_Account</label>
    <nameField>
        <label>IF_Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IF_Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_Account__c/fields/IFExternalKey__c.field-meta.xml
<CustomField>
    <fullName>IFExternalKey__c</fullName>
    <externalId>true</externalId>
    <label>IFExternalKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_Account__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>PostalCode</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HubCompanyRequest_Test.cls
/**
 * @description       : 
 * @author            : eunsu.kim
 * @group             : 
 * @last modified on  : 04-09-2026
 * @last modified by  : eunsu.kim
**/
// Code Coverage 95%, Test Execution Time 289ms
@isTest
public class HubCompanyRequest_Test {
    // Code Coverage 93%
    @isTest
    static void companyRequestTestSuccess() {
        IF_HubspotMockFactory.testCase = 'SUCCESS';
        IF_HubspotMockFactory.targetObject = 'companies';
        Test.setMock(HttpCalloutMock.class, new IF_HubspotMockFactory());
        Test.startTest();
        HubCompanyRequest.hubCompanyRequest();
        Test.stopTest();

        List<IF_Account__c> resultList = [SELECT Id, Name, IFExternalKey__c, PostalCode__c, Domain__c FROM IF_Account__c];
        System.assertEquals(1, resultList.size(), '데이터 1건 생성되어야 합니다');
        
        IF_Account__c res = resultList[0];
    }

    // Code Coverage 38%
    @isTest
    static void meetingLogRequestTestFail() {
        IF_HubspotMockFactory.testCase = 'ERROR';
        IF_HubspotMockFactory.targetObject = 'companies';
        Test.setMock(HttpCalloutMock.class, new IF_HubspotMockFactory());
        Test.startTest();
        HubCompanyRequest.hubCompanyRequest();
        Test.stopTest();

        List<IF_Account__c> resultList = [SELECT Id FROM IF_Account__c];

        System.assertEquals(0, resultList.size(), '에러 시 데이터가 생성되면 안됩니다');
    }
}