force-app/main/default/objects/IF_MeetingLog__c/IF_MeetingLog__c.object-meta.xml
<CustomObject>
    <label>IF_MeetingLog</label>
    <nameField>
        <label>IF_MeetingLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IF_MeetingLog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_MeetingLog__c/fields/AccountIFExternalKey__c.field-meta.xml
<CustomField>
    <fullName>AccountIFExternalKey__c</fullName>
    <label>AccountIFExternalKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IF_MeetingLog__c/fields/IFExternalKey__c.field-meta.xml
<CustomField>
    <fullName>IFExternalKey__c</fullName>
    <externalId>true</externalId>
    <label>IFExternalKey</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IF_MeetingLog__c/fields/StartAllDay__c.field-meta.xml
<CustomField>
    <fullName>StartAllDay__c</fullName>
    <label>Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MeetingLog__c/MeetingLog__c.object-meta.xml
<CustomObject>
    <label>회의록</label>
    <nameField>
        <label>Meeting Log Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>회의록</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MeetingLog__c/fields/IFExternalKey__c.field-meta.xml
<CustomField>
    <fullName>IFExternalKey__c</fullName>
    <externalId>true</externalId>
    <label>IFExternalKey</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MeetingLog__c/fields/SoldTo__c.field-meta.xml
<CustomField>
    <fullName>SoldTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup 고객사</description>
    <label>Sold to</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>회의록</relationshipLabel>
    <relationshipName>MeetingLog</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MeetingLog__c/fields/StartAllDay__c.field-meta.xml
<CustomField>
    <fullName>StartAllDay__c</fullName>
    <label>Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/IF_HubMeetingBatch_Test.cls
/**
 * @description       : 
 * @author            : eunsu.kim
 * @group             : 
 * @last modified on  : 04-09-2026
 * @last modified by  : eunsu.kim
**/
@isTest
private class IF_HubMeetingBatch_Test {

    @isTest
    static void testBatchExecution() {

        List<Account> accList = new List<Account>();

        for (Integer i = 0; i < 3; i++) {
            Account acc = new Account();
            acc.Name = 'Account ' + i;
            acc.IFExternalKey__c = 'ACC_KEY' + i;
            acc.PostalCode__c = '12345';
            accList.add(acc);
        }

        insert accList;

        List<IF_MeetingLog__c> ifList = new List<IF_MeetingLog__c>();

        for (Integer i = 0; i < 5; i++) {
            IF_MeetingLog__c obj = new IF_MeetingLog__c();
            obj.Name = 'Meeting ' + i;
            obj.StartAllDay__c = Date.today();
            obj.IFExternalKey__c = 'MEETING_KEY' + i;

            if (i < 3) {
                obj.AccountIFExternalKey__c = 'ACC_KEY' + i;
            }

            obj.IsConverted__c = false;
            ifList.add(obj);
        }

        insert ifList;

        Test.startTest();
        Database.executeBatch(new IF_HubMeetingBatch(), 200);
        Test.stopTest();

        List<MeetingLog__c> meetingList = [
            SELECT Id, IFExternalKey__c, SoldTo__c
            FROM MeetingLog__c
            WHERE IFExternalKey__c LIKE 'MEETING_KEY%'
        ];

        System.assert(meetingList.size() > 0);

        for (MeetingLog__c m : meetingList) {
            if (m.IFExternalKey__c == 'MEETING_KEY0' ||
                m.IFExternalKey__c == 'MEETING_KEY1' ||
                m.IFExternalKey__c == 'MEETING_KEY2') {

                System.assertNotEquals(null, m.SoldTo__c);
            }
        }

        List<IF_MeetingLog__c> updatedList = [
            SELECT Id, IsConverted__c
            FROM IF_MeetingLog__c
            WHERE IFExternalKey__c LIKE 'MEETING_KEY%'
        ];

        for (IF_MeetingLog__c obj : updatedList) {
            System.assertEquals(true, obj.IsConverted__c);
        }
    }
}