force-app/main/default/objects/MeetingLog__c/MeetingLog__c.object-meta.xml
<CustomObject>
    <label>회의록</label>
    <nameField>
        <label>Meeting Log Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>회의록</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MeetingLog__c/fields/Contents__c.field-meta.xml
<CustomField>
    <fullName>Contents__c</fullName>
    <label>Meeting Log (Contents)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MeetingLog__c/fields/EndAllDay__c.field-meta.xml
<CustomField>
    <fullName>EndAllDay__c</fullName>
    <formula>StartAllDay__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MeetingLog__c/fields/EndNotAllDay__c.field-meta.xml
<CustomField>
    <fullName>EndNotAllDay__c</fullName>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MeetingLog__c/fields/SoldTo2__c.field-meta.xml
<CustomField>
    <fullName>SoldTo2__c</fullName>
    <formula>Task__r.AccountName__c</formula>
    <label>Sold to</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MeetingLog__c/fields/StartAllDay__c.field-meta.xml
<CustomField>
    <fullName>StartAllDay__c</fullName>
    <label>Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MeetingLog__c/fields/StartNotAllDay__c.field-meta.xml
<CustomField>
    <fullName>StartNotAllDay__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MeetingLog__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task</label>
    <referenceTo>Calendar__c</referenceTo>
    <relationshipLabel>회의록</relationshipLabel>
    <relationshipName>Calendar</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NX_DownloadMeetingLogExcelController.cls
public with sharing class NX_DownloadMeetingLogExcelController {
    @AuraEnabled
    public static List<MeetingLog__c> getEvents(Id recordId, Id lastRecordId, Datetime lastCreatedDate, Integer limitSize) {
        String query = 'SELECT Id, Name, Task__c, SoldTo2__c, StartNotAllDay__c, StartAllDay__c, EndNotAllDay__c, EndAllDay__c, Contents__c ' +
                       'FROM MeetingLog__c ';
        
        List<String> conditions = new List<String>();

        try {
            if (lastRecordId != null && lastCreatedDate != null) {
                conditions.add('(CreatedDate < :lastCreatedDate OR (CreatedDate = :lastCreatedDate AND Id < :lastRecordId))');
            }
    
            if (!conditions.isEmpty()) {
                query += ' WHERE ' + String.join(conditions, ' AND ');
            }
    
            query += ' ORDER BY CreatedDate DESC, Id DESC LIMIT :limitSize';
        } catch (Exception e) {
            System.debug(e.getMessage() + 'line : ' + e.getLineNumber());
        }

        return Database.query(query);
    }
}